### ISSUE TITLE
String test 3 hang

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#219]
**Reported by mycae on 5 Jul 39446071 08:53 UTC**
String test 3 hangs on make test.

I am building on fedora 10, using gcc-4.3. I couldn't quite work out the hang completely, as I haven't quite worked out how the macros work for the testing code.

If you can provide some suggestions I will do my best to work out why this is happening.

The backtrace from gcc is:
(gdb) bt
#0  memchr () at ../sysdeps/i386/memchr.S:233
#1  0x0454dc48 in std::char_traits<char>::find ()
    at /usr/src/debug/gcc-4.3.2-20081105/obj-i386-redhat-linux/i386-redhat-linux/libstdc++-v3/include/bits/char_traits.h:266
#2  std::string::find (this=0xbfaf05c4, __c=<value optimized out>, 
    __pos=370546198)
    at /usr/src/debug/gcc-4.3.2-20081105/obj-i386-redhat-linux/i386-redhat-linux/libstdc++-v3/include/bits/basic_string.tcc:743
#3  0x08074e6d in BALL::String::has ()
    at /home/makerpm/rpmbuild/BUILD/BALL-1.2/include/BALL/DATATYPE/string.iC:601
#4  main (argc=Cannot access memory at address 0x1b1f1c36
) at String_test3.C:511
Current language:  auto; currently asm
(gdb) finish
Run till exit from #0  memchr () at ../sysdeps/i386/memchr.S:233
std::string::find (this=0xbfaf05c4, __c=<value optimized out>, __pos=0)
    at /usr/src/debug/gcc-4.3.2-20081105/obj-i386-redhat-linux/i386-redhat-linux/libstdc++-v3/include/bits/basic_string.tcc:744
744		  if (__p)
Current language:  auto; currently c++
(gdb) finish
Run till exit from #0  std::string::find (this=0xbfaf05c4, 
    __c=<value optimized out>, __pos=0)
    at /usr/src/debug/gcc-4.3.2-20081105/obj-i386-redhat-linux/i386-redhat-linux/libstdc++-v3/include/bits/basic_string.tcc:744
0x08074e6d in BALL::String::has ()
    at /home/makerpm/rpmbuild/BUILD/BALL-1.2/include/BALL/DATATYPE/string.iC:601
601	  return ((c != (char)0) && (find(c, 0) != string::npos));
Value returned is $1 = 4294967295
(gdb) finish
Run till exit from #0  0x08074e6d in BALL::String::has ()
    at /home/makerpm/rpmbuild/BUILD/BALL-1.2/include/BALL/DATATYPE/string.iC:601
main (argc=Cannot access memory at address 0x1b1f1c36
) at String_test3.C:511
511			TEST_EQUAL(String::isWhitespace(c), char_class.has(c))
(gdb) 

511			TEST_EQUAL(String::isWhitespace(c), char_class.has(c))

**Comment by anhi** [comment]
**Commented by anhi on 16 Jun 39456574 01:20 UTC**
Thanks for reporting this! This looks strange indeed, and we have not seen this before... Just to be on the safe side: could you rerun this test with LANG=C exported in your shell?

**Comment by anhi** [comment]
**Commented by anhi on 27 Nov 39456579 19:06 UTC**
One more thing: your path says 

BALL-1.2

is this correct? A lot of things changed between 1.2 and 1.3beta1 so maybe this is already resolved somehow?

**Comment by anhi** [comment]
**Commented by anhi on 21 Jul 40098895 00:26 UTC**
Since String_test3 seems to work fine, I am closing this bug.
