### ISSUE TITLE
CHARMM problem

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#41]
**Reported by Andreas Moll on 11 Oct 38774452 16:00 UTC**
Formaldehyd causes our CHARMM implementation to crash:
#0  0xb560c409 in BALL::QuadraticAngleBend::assignParameters (this=0x83cb970,
    parameters=@0xbfa49514, I=2, J=-1, K=-1) at quadraticAngleBend.C:199
#1  0xb553c9c0 in BALL::CharmmBend::setup (this=0x83cb948) at charmmBend.C:107
The problem seems to be, that no checks are done if the atom types are well defined. I guess that
this problem will also show up on other points in the code.

**Comment by anhi** [comment]
**Commented by admin on 4 Feb 38774453 09:46 UTC**
This has been fixed by the new sanity checks for the force
