### ISSUE TITLE
MOL2 file opening crashes

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#47]
**Reported by Andreas Moll on 4 Mar 38774499 02:40 UTC**
I have written a MOL2 file with BALLView, which when opened again crashes the application,
#0  0xb51ff28d in BALL::Composite::isDescendantOf (this=0x11, composite=@0x93fca48) at
composite.C:1371
#1  0xb5201ece in BALL::Composite::appendChild (this=0x11, composite=@0x93fca48) at composite.C:627
#2  0xb530f11a in BALL::AtomContainer::append (this=0x11, atom=@0x93fca48) at atomContainer.C:304
#3  0xb530f144 in BALL::AtomContainer::insert (this=0x11, atom=@0x93fca48) at atomContainer.C:310
#4  0xb52ad980 in BALL::MOL2File::buildAll_ (this=0xbfbbdd64, system=@0x8f094c8) at MOL2File.C:775
#5  0xb52af91a in BALL::MOL2File::read (this=0xbfbbdd64, system=@0x8f094c8) at MOL2File.C:320
#6  0xb52735fd in BALL::GenericMolFile::operator>> (this=0xbfbbdd64, system=@0x8f094c8) at
genericMolFile.C:102
#7  0xb7c1c9f0 in BALL::VIEW::MolecularFileDialog::readMOL2File (this=0x83bada0,
filename=@0xbfbbf094,
    system_name=@0xbfbbf08c) at molecularFileDialog.C:506
The file seem to be ok, because it can be correctly read with chimera.

'''Solution:''' The reason for the crash are the substructure ids in the MOL2 file. These are 0, while BALL assumes that ids start at 1. I don't know why BALL produced the wrong ids in the first place (maybe we write our internal indexing which starts at zero, but I couldn't reproduce that... Maybe Oliver should look into that?) but we might either choose to throw an exception when we encounter a case like that or use the appended fix to make the code more stable. Any preferences, Oliver?

**Comment by anhi** [comment]
**Commented by admin on 21 Oct 38774499 14:13 UTC**
I've added the respective test file as a test case to MOL2File_test.
Andreas (H) could you integrate your patch into the V1_2 branch and make sure
MOL2File_test works as expected?

**Comment by anhi** [comment]
**Commented by admin on 13 Apr 38774500 04:53 UTC**
Patch has been commited to V1_2
